import type {Atlas} from './anatomy';

// ─── Full-name overrides (highest priority) ───

const OVERRIDES: Record<string, string> = {
  'heart': 'Coração',
  'brain': 'Cérebro',
  'liver': 'Fígado',
  'stomach': 'Estômago',
  'spleen': 'Baço',
  'pancreas': 'Pâncreas',
  'urinary bladder': 'Bexiga urinária',
  'trachea': 'Traqueia',
  'diaphragm': 'Diafragma',
  'lung': 'Pulmão',
  'right lung': 'Pulmão direito',
  'left lung': 'Pulmão esquerdo',
  'kidney': 'Rim',
  'right kidney': 'Rim direito',
  'left kidney': 'Rim esquerdo',
  'esophagus': 'Esôfago',
  'larynx': 'Laringe',
  'pharynx': 'Faringe',
  'thyroid gland': 'Glândula tireoide',
  'adrenal gland': 'Glândula suprarrenal',
  'right adrenal gland': 'Glândula suprarrenal direita',
  'left adrenal gland': 'Glândula suprarrenal esquerda',
  'prostate': 'Próstata',
  'testis': 'Testículo',
  'right testis': 'Testículo direito',
  'left testis': 'Testículo esquerdo',
  'penis': 'Pênis',
  'uterus': 'Útero',
  'ovary': 'Ovário',
  'gallbladder': 'Vesícula biliar',
  'appendix': 'Apêndice',
  'duodenum': 'Duodeno',
  'jejunum': 'Jejuno',
  'ileum': 'Íleo',
  'cecum': 'Ceco',
  'rectum': 'Reto',
  'colon': 'Cólon',
  'sigmoid colon': 'Cólon sigmoide',
  'transverse colon': 'Cólon transverso',
  'ascending colon': 'Cólon ascendente',
  'descending colon': 'Cólon descendente',
  'small intestine': 'Intestino delgado',
  'large intestine': 'Intestino grosso',
  'aorta': 'Aorta',
  'ascending aorta': 'Aorta ascendente',
  'descending aorta': 'Aorta descendente',
  'abdominal aorta': 'Aorta abdominal',
  'arch of aorta': 'Arco da aorta',
  'thoracic aorta': 'Aorta torácica',
  'superior vena cava': 'Veia cava superior',
  'inferior vena cava': 'Veia cava inferior',
  'portal vein': 'Veia porta',
  'hepatic portal vein': 'Veia porta hepática',
  'pulmonary artery': 'Artéria pulmonar',
  'pulmonary vein': 'Veia pulmonar',
  'segmental pulmonary vein': 'Veia pulmonar segmentar',
  'subsegmental pulmonary vein': 'Veia pulmonar subsegmentar',
  'femoral artery': 'Artéria femoral',
  'femoral vein': 'Veia femoral',
  'carotid artery': 'Artéria carótida',
  'common carotid artery': 'Artéria carótida comum',
  'right common carotid artery': 'Artéria carótida comum direita',
  'left common carotid artery': 'Artéria carótida comum esquerda',
  'internal carotid artery': 'Artéria carótida interna',
  'right internal carotid artery': 'Artéria carótida interna direita',
  'left internal carotid artery': 'Artéria carótida interna esquerda',
  'external carotid artery': 'Artéria carótida externa',
  'jugular vein': 'Veia jugular',
  'subclavian artery': 'Artéria subclávia',
  'right subclavian artery': 'Artéria subclávia direita',
  'left subclavian artery': 'Artéria subclávia esquerda',
  'subclavian vein': 'Veia subclávia',
  'axillary artery': 'Artéria axilar',
  'axillary vein': 'Veia axilar',
  'brachial artery': 'Artéria braquial',
  'radial artery': 'Artéria radial',
  'ulnar artery': 'Artéria ulnar',
  'tibial artery': 'Artéria tibial',
  'anterior tibial artery': 'Artéria tibial anterior',
  'posterior tibial artery': 'Artéria tibial posterior',
  'popliteal artery': 'Artéria poplítea',
  'popliteal vein': 'Veia poplítea',
  'renal artery': 'Artéria renal',
  'renal vein': 'Veia renal',
  'celiac artery': 'Tronco celíaco',
  'mesenteric artery': 'Artéria mesentérica',
  'superior mesenteric artery': 'Artéria mesentérica superior',
  'inferior mesenteric artery': 'Artéria mesentérica inferior',
  'coronary artery': 'Artéria coronária',
  'right coronary artery': 'Artéria coronária direita',
  'left coronary artery': 'Artéria coronária esquerda',
  'brachiocephalic artery': 'Tronco braquiocefálico',
  'common hepatic artery': 'Artéria hepática comum',
  'basilar artery': 'Artéria basilar',
  'vertebral artery': 'Artéria vertebral',
  'right vertebral artery': 'Artéria vertebral direita',
  'left vertebral artery': 'Artéria vertebral esquerda',
  'iliac artery': 'Artéria ilíaca',
  'common iliac artery': 'Artéria ilíaca comum',
  'right common iliac artery': 'Artéria ilíaca comum direita',
  'left common iliac artery': 'Artéria ilíaca comum esquerda',
  'internal iliac artery': 'Artéria ilíaca interna',
  'external iliac artery': 'Artéria ilíaca externa',
  'deep femoral artery': 'Artéria femoral profunda',
  'deep femoral vein': 'Veia femoral profunda',
  'anterior cerebral artery': 'Artéria cerebral anterior',
  'middle cerebral artery': 'Artéria cerebral média',
  'posterior cerebral artery': 'Artéria cerebral posterior',
  'anterior communicating artery': 'Artéria comunicante anterior',
  'posterior communicating artery': 'Artéria comunicante posterior',
  'ophthalmic artery': 'Artéria oftálmica',
  'anterior interventricular branch of left coronary artery': 'Ramo interventricular anterior da artéria coronária esquerda',
  'circumflex branch of left coronary artery': 'Ramo circunflexo da artéria coronária esquerda',
  'superior terminal branch of middle cerebral artery': 'Ramo terminal superior da artéria cerebral média',
  'posterior inferior cerebellar artery': 'Artéria cerebelar posteroinferior',
  'skull': 'Crânio',
  'mandible': 'Mandíbula',
  'maxilla': 'Maxila',
  'rib': 'Costela',
  'sternum': 'Esterno',
  'clavicle': 'Clavícula',
  'right clavicle': 'Clavícula direita',
  'left clavicle': 'Clavícula esquerda',
  'scapula': 'Escápula',
  'right scapula': 'Escápula direita',
  'left scapula': 'Escápula esquerda',
  'humerus': 'Úmero',
  'right humerus': 'Úmero direito',
  'left humerus': 'Úmero esquerdo',
  'radius': 'Rádio',
  'ulna': 'Ulna',
  'femur': 'Fêmur',
  'right femur': 'Fêmur direito',
  'left femur': 'Fêmur esquerdo',
  'tibia': 'Tíbia',
  'right tibia': 'Tíbia direita',
  'left tibia': 'Tíbia esquerda',
  'fibula': 'Fíbula',
  'right fibula': 'Fíbula direita',
  'left fibula': 'Fíbula esquerda',
  'patella': 'Patela',
  'right patella': 'Patela direita',
  'left patella': 'Patela esquerda',
  'pelvis': 'Pelve',
  'sacrum': 'Sacro',
  'coccyx': 'Cóccix',
  'vertebra': 'Vértebra',
  'cervical vertebra': 'Vértebra cervical',
  'thoracic vertebra': 'Vértebra torácica',
  'lumbar vertebra': 'Vértebra lombar',
  'atlas': 'Atlas (C1)',
  'axis': 'Áxis (C2)',
  'hyoid bone': 'Osso hioide',
  'tooth': 'Dente',
  'head': 'Cabeça',
  'neck': 'Pescoço',
  'thorax': 'Tórax',
  'abdomen': 'Abdome',
  'trunk': 'Tronco',
  'face': 'Face',
  'nose': 'Nariz',
  'ear': 'Orelha',
  'right ear': 'Orelha direita',
  'left ear': 'Orelha esquerda',
  'eye': 'Olho',
  'right eye': 'Olho direito',
  'left eye': 'Olho esquerdo',
  'eyeball': 'Globo ocular',
  'tongue': 'Língua',
  'palate': 'Palato',
  'lip': 'Lábio',
  'epiglottis': 'Epiglote',
  'thyroid cartilage': 'Cartilagem tireoide',
  'cricoid cartilage': 'Cartilagem cricoide',
  'arytenoid cartilage': 'Cartilagem aritenoide',
  'tympanic membrane': 'Membrana timpânica',
  'cochlea': 'Cóclea',
  'spinal cord': 'Medula espinhal',
  'cerebellum': 'Cerebelo',
  'cerebrum': 'Cérebro',
  'brainstem': 'Tronco encefálico',
  'pons': 'Ponte',
  'medulla oblongata': 'Bulbo (medula oblonga)',
  'hypothalamus': 'Hipotálamo',
  'thalamus': 'Tálamo',
  'hippocampus': 'Hipocampo',
  'corpus callosum': 'Corpo caloso',
  'pituitary gland': 'Hipófise',
  'pineal gland': 'Glândula pineal',
  'optic nerve': 'Nervo óptico',
  'trigeminal nerve': 'Nervo trigêmeo',
  'facial nerve': 'Nervo facial',
  'vagus nerve': 'Nervo vago',
  'sciatic nerve': 'Nervo ciático',
  'median nerve': 'Nervo mediano',
  'ulnar nerve': 'Nervo ulnar',
  'radial nerve': 'Nervo radial',
  'femoral nerve': 'Nervo femoral',
  'tibial nerve': 'Nervo tibial',
  'brachial plexus': 'Plexo braquial',
  'lumbar plexus': 'Plexo lombar',
  'sacral plexus': 'Plexo sacral',
  'ophthalmic nerve': 'Nervo oftálmico',
  'deltoid': 'Deltoide',
  'deltoid muscle': 'Músculo deltoide',
  'biceps brachii': 'Bíceps braquial',
  'triceps brachii': 'Tríceps braquial',
  'pectoralis major': 'Peitoral maior',
  'pectoralis minor': 'Peitoral menor',
  'trapezius': 'Trapézio',
  'latissimus dorsi': 'Grande dorsal',
  'rectus abdominis': 'Reto abdominal',
  'external oblique': 'Oblíquo externo',
  'internal oblique': 'Oblíquo interno',
  'transversus abdominis': 'Transverso do abdome',
  'gluteus maximus': 'Glúteo máximo',
  'gluteus medius': 'Glúteo médio',
  'gluteus minimus': 'Glúteo mínimo',
  'quadriceps femoris': 'Quadríceps femoral',
  'rectus femoris': 'Reto femoral',
  'vastus lateralis': 'Vasto lateral',
  'vastus medialis': 'Vasto medial',
  'vastus intermedius': 'Vasto intermédio',
  'sartorius': 'Sartório',
  'gracilis': 'Grácil',
  'adductor longus': 'Adutor longo',
  'adductor brevis': 'Adutor curto',
  'adductor magnus': 'Adutor magno',
  'biceps femoris': 'Bíceps femoral',
  'semitendinosus': 'Semitendíneo',
  'semimembranosus': 'Semimembranáceo',
  'gastrocnemius': 'Gastrocnêmio',
  'soleus': 'Sóleo',
  'tibialis anterior': 'Tibial anterior',
  'tibialis posterior': 'Tibial posterior',
  'achilles tendon': 'Tendão de Aquiles',
  'calcaneal tendon': 'Tendão calcâneo',
  'sternocleidomastoid': 'Esternocleidomastóideo',
  'masseter': 'Masseter',
  'temporalis': 'Temporal',
  'orbicularis oculi': 'Orbicular do olho',
  'orbicularis oris': 'Orbicular da boca',
  'intercostal muscle': 'Músculo intercostal',
  'psoas major': 'Psoas maior',
  'iliacus': 'Ilíaco',
  'piriformis': 'Piriforme',
  'tensor fasciae latae': 'Tensor da fáscia lata',
  'flexor digitorum superficialis': 'Flexor superficial dos dedos',
  'flexor digitorum profundus': 'Flexor profundo dos dedos',
  'extensor digitorum': 'Extensor dos dedos',
  'flexor carpi radialis': 'Flexor radial do carpo',
  'flexor carpi ulnaris': 'Flexor ulnar do carpo',
  'extensor carpi radialis longus': 'Extensor radial longo do carpo',
  'extensor carpi radialis brevis': 'Extensor radial curto do carpo',
  'extensor carpi ulnaris': 'Extensor ulnar do carpo',
  'abductor pollicis longus': 'Abdutor longo do polegar',
  'abductor pollicis brevis': 'Abdutor curto do polegar',
  'extensor pollicis longus': 'Extensor longo do polegar',
  'extensor pollicis brevis': 'Extensor curto do polegar',
  'flexor pollicis longus': 'Flexor longo do polegar',
  'abductor digiti minimi': 'Abdutor do dedo mínimo',
  'flexor digiti minimi brevis': 'Flexor curto do dedo mínimo',
  'erector spinae': 'Eretor da espinha',
  'intervertebral disk': 'Disco intervertebral',
  'intervertebral disc': 'Disco intervertebral',
  'serratus anterior': 'Serrátil anterior',
  'levator scapulae': 'Elevador da escápula',
  'supraspinatus': 'Supraespinal',
  'infraspinatus': 'Infraespinal',
  'subscapularis': 'Subescapular',
  'teres minor': 'Redondo menor',
  'teres major': 'Redondo maior',
  'rhomboid major': 'Romboide maior',
  'rhomboid minor': 'Romboide menor',
  'peroneus longus': 'Fibular longo',
  'peroneus brevis': 'Fibular curto',
  'supinator': 'Supinador',
  'pronator teres': 'Pronador redondo',
  'skin': 'Pele',
  'fascia': 'Fáscia',
  'tendon': 'Tendão',
  'ligament': 'Ligamento',
  'cartilage': 'Cartilagem',
  'bone': 'Osso',
  'bone organ': 'Osso',
  'joint': 'Articulação',
  'muscle': 'Músculo',
  'muscle organ': 'Músculo',
  'nerve': 'Nervo',
  'artery': 'Artéria',
  'vein': 'Veia',
  'lymph node': 'Linfonodo',
  'gland': 'Glândula',
  'body proper': 'Corpo próprio',
  'human body': 'Corpo humano',
  'physical anatomical entity': 'Entidade anatômica física',
  'anatomical entity': 'Entidade anatômica',
  'material anatomical entity': 'Entidade anatômica material',
  'anatomical structure': 'Estrutura anatômica',
  'cardinal organ part': 'Parte cardinal de órgão',
  'organ region': 'Região de órgão',
  'organ segment': 'Segmento de órgão',
  'organ': 'Órgão',
  'solid organ': 'Órgão sólido',
  'cavitated organ': 'Órgão cavitado',
  'organ zone': 'Zona de órgão',
  'organ component': 'Componente de órgão',
  'set of organs': 'Conjunto de órgãos',
  'set of arteries': 'Conjunto de artérias',
  'musculature': 'Musculatura',
  'cardiovascular system': 'Sistema cardiovascular',
  'respiratory system': 'Sistema respiratório',
  'nervous system': 'Sistema nervoso',
  'digestive system': 'Sistema digestório',
  'alimentary system': 'Sistema alimentar',
  'urinary system': 'Sistema urinário',
  'reproductive system': 'Sistema reprodutor',
  'lymphatic system': 'Sistema linfático',
  'endocrine system': 'Sistema endócrino',
  'integumentary system': 'Sistema tegumentar',
  'musculoskeletal system': 'Sistema musculoesquelético',
  'skeletal system': 'Sistema esquelético',
  'skeleton (in vivo)': 'Esqueleto (in vivo)',
  'axial skeletal system': 'Sistema esquelético axial',
  'vasculature of body': 'Vasculatura do corpo',
  'vascular tree': 'Árvore vascular',
  'systemic artery': 'Artéria sistêmica',
  'systemic vein': 'Veia sistêmica',
  'systemic arterial system': 'Sistema arterial sistêmico',
  'systemic venous system': 'Sistema venoso sistêmico',
  'systemic arterial tree': 'Árvore arterial sistêmica',
  'portal venous system': 'Sistema venoso portal',
  'portal venous tree': 'Árvore venosa portal',
  'pulmonary vascular system': 'Sistema vascular pulmonar',
  'pulmonary arterial tree': 'Árvore arterial pulmonar',
  'arterial trunk': 'Tronco arterial',
  'systemic arterial trunk': 'Tronco arterial sistêmico',
  'venous trunk': 'Tronco venoso',
  'region of vascular tree organ': 'Região da árvore vascular',
  'segment of artery': 'Segmento de artéria',
  'variant artery': 'Artéria variante',
  'segment of arterial tree organ': 'Segmento da árvore arterial',
  'segment of venous tree organ': 'Segmento da árvore venosa',
  'inferior systemic venous tree': 'Árvore venosa sistêmica inferior',
  'gastrointestinal tract': 'Trato gastrointestinal',
  'lower gastrointestinal tract': 'Trato gastrointestinal inferior',
  'respiratory tract': 'Trato respiratório',
  'lower respiratory tract': 'Trato respiratório inferior',
  'tracheobronchial tree': 'Árvore traqueobrônquica',
  'segment of tracheobronchial tree': 'Segmento da árvore traqueobrônquica',
  'segment of bronchial tree': 'Segmento da árvore brônquica',
  'pulmonary segment of bronchial tree': 'Segmento pulmonar da árvore brônquica',
  'thoracic part of tracheobronchial tree': 'Parte torácica da árvore traqueobrônquica',
  'body cavity content': 'Conteúdo da cavidade corporal',
  'content of thorax': 'Conteúdo do tórax',
  'content of mediastinum': 'Conteúdo do mediastino',
  'content of superior mediastinum': 'Conteúdo do mediastino superior',
  'content of inferior mediastinum': 'Conteúdo do mediastino inferior',
  'content of middle mediastinum': 'Conteúdo do mediastino médio',
  'mediastinum': 'Mediastino',
  'superior mediastinum': 'Mediastino superior',
  'inferior mediastinum': 'Mediastino inferior',
  'middle mediastinum': 'Mediastino médio',
  'body compartment': 'Compartimento corporal',
  'compartment of thorax': 'Compartimento do tórax',
  'right pulmopleural compartment': 'Compartimento pulmopleural direito',
  'left pulmopleural compartment': 'Compartimento pulmopleural esquerdo',
  'body wall': 'Parede corporal',
  'chest wall': 'Parede torácica',
  'wall of abdomen': 'Parede abdominal',
  'anterior thoracic wall': 'Parede torácica anterior',
  'anterior chest': 'Tórax anterior',
  'back of thorax': 'Dorso do tórax',
  'thoracic segment of trunk': 'Segmento torácico do tronco',
  'abdominal segment of trunk': 'Segmento abdominal do tronco',
  'head proper': 'Cabeça propriamente dita',
  'nonparenchymatous organ': 'Órgão não parenquimatoso',
  'organ with cavitated organ parts': 'Órgão com partes cavitadas',
  'right lobe of liver': 'Lobo direito do fígado',
  'left lobe of liver': 'Lobo esquerdo do fígado',
  'upper lobe of right lung': 'Lobo superior do pulmão direito',
  'middle lobe of lung': 'Lobo médio do pulmão',
  'lower lobe of right lung': 'Lobo inferior do pulmão direito',
  'upper lobe of left lung': 'Lobo superior do pulmão esquerdo',
  'right hand': 'Mão direita',
  'left hand': 'Mão esquerda',
  'right foot': 'Pé direito',
  'left foot': 'Pé esquerdo',
  'right free lower limb': 'Membro inferior livre direito',
  'left free lower limb': 'Membro inferior livre esquerdo',
  'right cerebral hemisphere': 'Hemisfério cerebral direito',
  'left cerebral hemisphere': 'Hemisfério cerebral esquerdo',
  'right side of rib cage': 'Lado direito da caixa torácica',
  'left side of rib cage': 'Lado esquerdo da caixa torácica',
  'pancreaticobiliary system': 'Sistema pancreatobiliar',
  'thoracic vertebral column': 'Coluna vertebral torácica',
  'phalanx of finger': 'Falange do dedo da mão',
  'phalanx of toe': 'Falange do dedo do pé',
  'muscle of foot': 'Músculo do pé',
  'intrinsic muscle of foot': 'Músculo intrínseco do pé',
  'intrinsic muscle of plantar part of foot': 'Músculo intrínseco plantar do pé',
  'muscle of leg': 'Músculo da perna',
  'muscle of thigh': 'Músculo da coxa',
  'muscle of shoulder': 'Músculo do ombro',
  'muscle of trunk': 'Músculo do tronco',
  'muscle of head': 'Músculo da cabeça',
  'muscle of lower limb': 'Músculo do membro inferior',
  'muscle of upper limb': 'Músculo do membro superior',
  'muscle of free lower limb': 'Músculo do membro inferior livre',
  'muscle of pectoral girdle': 'Músculo da cintura peitoral',
  'muscle of pelvic girdle': 'Músculo da cintura pélvica',
  'muscle of posterior compartment of forearm': 'Músculo do compartimento posterior do antebraço',
  'muscle of vertebral column': 'Músculo da coluna vertebral',
  'gluteal muscle': 'Músculo glúteo',
  'superficial postvertebral muscle': 'Músculo pós-vertebral superficial',
  'deep postvertebral muscle': 'Músculo pós-vertebral profundo',
  'skeletal system of trunk': 'Sistema esquelético do tronco',
  'skeletal system of thorax': 'Sistema esquelético do tórax',
  'white matter of neuraxis': 'Substância branca do neuroeixo',
  'gyrus of neuraxis': 'Giro do neuroeixo',
  'neuraxis': 'Neuroeixo',
  'long bone': 'Osso longo',
  'basal segmental bronchial tree': 'Árvore brônquica segmentar basal',
  'segment of renal artery': 'Segmento da artéria renal',
  'right superior pulmonary vein': 'Veia pulmonar superior direita',
  'left superior pulmonary vein': 'Veia pulmonar superior esquerda',
  'right inferior pulmonary vein': 'Veia pulmonar inferior direita',
  'left inferior pulmonary vein': 'Veia pulmonar inferior esquerda',
  'right upper lobar artery': 'Artéria lobar superior direita',
  'right lower lobar artery': 'Artéria lobar inferior direita',
  'left lower lobar artery': 'Artéria lobar inferior esquerda',
  'right upper lobar vein': 'Veia lobar superior direita',
  'left upper lobar vein': 'Veia lobar superior esquerda',
  'zone of jejunum': 'Zona do jejuno',
  'branch of cranial nerve': 'Ramo de nervo craniano',
  'branch of trigeminal nerve': 'Ramo do nervo trigêmeo',
  'branch of ophthalmic nerve': 'Ramo do nervo oftálmico',
  'articular disk of symphysis': 'Disco articular da sínfise',
  'subdivision of common carotid artery': 'Subdivisão da artéria carótida comum',
  'subdivision of internal carotid artery': 'Subdivisão da artéria carótida interna',
  'subdivision of cerebral part of internal carotid artery': 'Subdivisão da parte cerebral da artéria carótida interna',
  'subdivision of common hepatic artery': 'Subdivisão da artéria hepática comum',
  'subdivision of hepatic artery proper': 'Subdivisão da artéria hepática própria',
  'subdivision of inferior vena caval tree': 'Subdivisão da árvore da veia cava inferior',
  'subdivision of superior vena caval tree': 'Subdivisão da árvore da veia cava superior',
  'subdivision of subclavian artery': 'Subdivisão da artéria subclávia',
  'subdivision of pre-hepatic portal vein': 'Subdivisão da veia porta pré-hepática',
  'right superior bronchopulmonary segment': 'Segmento broncopulmonar superior direito',
  'right apical bronchopulmonary segment': 'Segmento broncopulmonar apical direito',
  'right posterior bronchopulmonary segment': 'Segmento broncopulmonar posterior direito',
  'right anterior bronchopulmonary segment': 'Segmento broncopulmonar anterior direito',
  'right posterior basal bronchopulmonary segment': 'Segmento broncopulmonar basal posterior direito',
  'left anterior bronchopulmonary segment': 'Segmento broncopulmonar anterior esquerdo',
  'left apical bronchopulmonary segment': 'Segmento broncopulmonar apical esquerdo',
  'apicoposterior bronchopulmonary segment': 'Segmento broncopulmonar apicoposterior',
  'right common basal vein': 'Veia basal comum direita',
  'apicoposterior segmental vein': 'Veia segmentar apicoposterior',
  'posterior segmental vein': 'Veia segmentar posterior',
  'anastomosis': 'Anastomose',
  'vascular anastomosis': 'Anastomose vascular',
  'arterial anastomosis': 'Anastomose arterial',
  'venous anastomosis': 'Anastomose venosa',
  'right conus artery': 'Artéria do cone direita',
  'left conus artery': 'Artéria do cone esquerda',
  'forebrain': 'Prosencéfalo',
  'midbrain': 'Mesencéfalo',
  'hindbrain': 'Rombencéfalo',
  'telencephalon': 'Telencéfalo',
  'diencephalon': 'Diencéfalo',
  'retina': 'Retina',
  'iris': 'Íris',
  'cornea': 'Córnea',
  'lens': 'Cristalino',
  'choroid': 'Coroide',
  'sclera': 'Esclera',
  'conjunctiva': 'Conjuntiva',
  'optic chiasm': 'Quiasma óptico',
  'pelvic girdle': 'Cintura pélvica',
  'pectoral girdle': 'Cintura peitoral',
  'shoulder girdle': 'Cintura escapular',
  'rib cage': 'Caixa torácica',
  'vertebral column': 'Coluna vertebral',
  'spinal column': 'Coluna vertebral',
  'cauda equina': 'Cauda equina',
  'meninges': 'Meninges',
  'dura mater': 'Dura-máter',
  'arachnoid': 'Aracnoide',
  'pia mater': 'Pia-máter',
  'periosteum': 'Periósteo',
  'perichondrium': 'Pericôndrio',
  'peritoneum': 'Peritônio',
  'pleura': 'Pleura',
  'pericardium': 'Pericárdio',
  'endocardium': 'Endocárdio',
  'myocardium': 'Miocárdio',
  'epicardium': 'Epicárdio',
  'mitral valve': 'Válvula mitral',
  'tricuspid valve': 'Válvula tricúspide',
  'aortic valve': 'Válvula aórtica',
  'pulmonary valve': 'Válvula pulmonar',
  'bronchus': 'Brônquio',
  'right bronchus': 'Brônquio direito',
  'left bronchus': 'Brônquio esquerdo',
  'alveolus': 'Alvéolo',
  'ureter': 'Ureter',
  'urethra': 'Uretra',
  'epididymis': 'Epidídimo',
  'seminal vesicle': 'Vesícula seminal',
  'vas deferens': 'Ducto deferente',
  'scrotum': 'Escroto',
  'glans penis': 'Glande peniana',
  'prepuce': 'Prepúcio',
  'perineum': 'Períneo',
  'anus': 'Ânus',
  'sigmoid': 'Sigmoide',
  'mesentery': 'Mesentério',
  'omentum': 'Omento',
  'peritoneal cavity': 'Cavidade peritoneal',
  'thoracic cavity': 'Cavidade torácica',
  'abdominal cavity': 'Cavidade abdominal',
  'nasal cavity': 'Cavidade nasal',
  'oral cavity': 'Cavidade oral',
  'cranial cavity': 'Cavidade craniana',
  'bone marrow': 'Medula óssea',
  'thymus': 'Timo',
  'tonsil': 'Tonsila',
  'palatine tonsil': 'Tonsila palatina',
  'parotid gland': 'Glândula parótida',
  'submandibular gland': 'Glândula submandibular',
  'sublingual gland': 'Glândula sublingual',
  'lacrimal gland': 'Glândula lacrimal',
  'sebaceous gland': 'Glândula sebácea',
  'sweat gland': 'Glândula sudorípara',
  'mammary gland': 'Glândula mamária',
  'parathyroid gland': 'Glândula paratireoide',
};

// ─── Nouns (feminine/masculine) — used for word-level translation + gender ───
// Gender: 'f' = feminine, 'm' = masculine

type Gender = 'f' | 'm';
const NOUNS: Record<string, [string, Gender]> = {
  'artery': ['artéria', 'f'],
  'arteries': ['artérias', 'f'],
  'vein': ['veia', 'f'],
  'veins': ['veias', 'f'],
  'nerve': ['nervo', 'm'],
  'nerves': ['nervos', 'm'],
  'muscle': ['músculo', 'm'],
  'muscles': ['músculos', 'm'],
  'bone': ['osso', 'm'],
  'bones': ['ossos', 'm'],
  'ligament': ['ligamento', 'm'],
  'tendon': ['tendão', 'm'],
  'cartilage': ['cartilagem', 'f'],
  'fascia': ['fáscia', 'f'],
  'gland': ['glândula', 'f'],
  'organ': ['órgão', 'm'],
  'trunk': ['tronco', 'm'],
  'branch': ['ramo', 'm'],
  'branches': ['ramos', 'm'],
  'tributary': ['tributária', 'f'],
  'tributaries': ['tributárias', 'f'],
  'segment': ['segmento', 'm'],
  'subdivision': ['subdivisão', 'f'],
  'region': ['região', 'f'],
  'zone': ['zona', 'f'],
  'part': ['parte', 'f'],
  'parts': ['partes', 'f'],
  'lobe': ['lobo', 'm'],
  'tree': ['árvore', 'f'],
  'system': ['sistema', 'm'],
  'tract': ['trato', 'm'],
  'wall': ['parede', 'f'],
  'cavity': ['cavidade', 'f'],
  'body': ['corpo', 'm'],
  'head': ['cabeça', 'f'],
  'neck': ['pescoço', 'm'],
  'face': ['face', 'f'],
  'tooth': ['dente', 'm'],
  'eye': ['olho', 'm'],
  'ear': ['orelha', 'f'],
  'nose': ['nariz', 'm'],
  'mouth': ['boca', 'f'],
  'shoulder': ['ombro', 'm'],
  'arm': ['braço', 'm'],
  'forearm': ['antebraço', 'm'],
  'hand': ['mão', 'f'],
  'finger': ['dedo', 'm'],
  'thumb': ['polegar', 'm'],
  'wrist': ['punho', 'm'],
  'hip': ['quadril', 'm'],
  'thigh': ['coxa', 'f'],
  'knee': ['joelho', 'm'],
  'leg': ['perna', 'f'],
  'foot': ['pé', 'm'],
  'toe': ['dedo do pé', 'm'],
  'ankle': ['tornozelo', 'm'],
  'rib': ['costela', 'f'],
  'ribs': ['costelas', 'f'],
  'disk': ['disco', 'm'],
  'disc': ['disco', 'm'],
  'valve': ['válvula', 'f'],
  'cusp': ['cúspide', 'f'],
  'septum': ['septo', 'm'],
  'ventricle': ['ventrículo', 'm'],
  'atrium': ['átrio', 'm'],
  'membrane': ['membrana', 'f'],
  'capsule': ['cápsula', 'f'],
  'sheath': ['bainha', 'f'],
  'duct': ['ducto', 'm'],
  'canal': ['canal', 'm'],
  'tube': ['tubo', 'm'],
  'sac': ['saco', 'm'],
  'plexus': ['plexo', 'm'],
  'ganglion': ['gânglio', 'm'],
  'nucleus': ['núcleo', 'm'],
  'cortex': ['córtex', 'm'],
  'gyrus': ['giro', 'm'],
  'sulcus': ['sulco', 'm'],
  'fissure': ['fissura', 'f'],
  'sinus': ['seio', 'm'],
  'arch': ['arco', 'm'],
  'ring': ['anel', 'm'],
  'fold': ['prega', 'f'],
  'ridge': ['crista', 'f'],
  'crest': ['crista', 'f'],
  'process': ['processo', 'm'],
  'tubercle': ['tubérculo', 'm'],
  'condyle': ['côndilo', 'm'],
  'trochanter': ['trocanter', 'm'],
  'malleolus': ['maléolo', 'm'],
  'notch': ['incisura', 'f'],
  'surface': ['superfície', 'f'],
  'margin': ['margem', 'f'],
  'border': ['borda', 'f'],
  'apex': ['ápice', 'm'],
  'base': ['base', 'f'],
  'hilum': ['hilo', 'm'],
  'fundus': ['fundo', 'm'],
  'compartment': ['compartimento', 'm'],
  'content': ['conteúdo', 'm'],
  'set': ['conjunto', 'm'],
  'skeleton': ['esqueleto', 'm'],
  'hemisphere': ['hemisfério', 'm'],
  'limb': ['membro', 'm'],
  'phalanx': ['falange', 'f'],
  'vertebra': ['vértebra', 'f'],
  'vertebrae': ['vértebras', 'f'],
  'sphincter': ['esfíncter', 'm'],
  'pelvis': ['pelve', 'f'],
  'skin': ['pele', 'f'],
  'node': ['nodo', 'm'],
  'lobule': ['lóbulo', 'm'],
  'gingiva': ['gengiva', 'f'],
  'jaw': ['maxilar', 'm'],
  'retina': ['retina', 'f'],
  'iris': ['íris', 'f'],
  'cornea': ['córnea', 'f'],
  'choroid': ['coroide', 'f'],
  'girdle': ['cintura', 'f'],
  'column': ['coluna', 'f'],
  'cord': ['medula', 'f'],
  'aorta': ['aorta', 'f'],
  'division': ['divisão', 'f'],
  'layer': ['camada', 'f'],
  'plate': ['placa', 'f'],
  'band': ['banda', 'f'],
  'ramus': ['ramo', 'm'],
  'foramen': ['forame', 'm'],
  'fossa': ['fossa', 'f'],
  'meatus': ['meato', 'm'],
  'labrum': ['lábio', 'm'],
  'ileum': ['íleo', 'm'],
  'jejunum': ['jejuno', 'm'],
  'cecum': ['ceco', 'm'],
  'rectum': ['reto', 'm'],
  'colon': ['cólon', 'm'],
  'duodenum': ['duodeno', 'm'],
  'bronchus': ['brônquio', 'm'],
  'trachea': ['traqueia', 'f'],
  'larynx': ['laringe', 'f'],
  'pharynx': ['faringe', 'f'],
  'esophagus': ['esôfago', 'm'],
  'ureter': ['ureter', 'm'],
  'urethra': ['uretra', 'f'],
  'bladder': ['bexiga', 'f'],
  'prostate': ['próstata', 'f'],
  'penis': ['pênis', 'm'],
  'testis': ['testículo', 'm'],
  'epididymis': ['epidídimo', 'm'],
  'scrotum': ['escroto', 'm'],
  'spleen': ['baço', 'm'],
  'pancreas': ['pâncreas', 'm'],
  'liver': ['fígado', 'm'],
  'stomach': ['estômago', 'm'],
  'kidney': ['rim', 'm'],
  'lung': ['pulmão', 'm'],
  'diaphragm': ['diafragma', 'm'],
  'sternum': ['esterno', 'm'],
  'clavicle': ['clavícula', 'f'],
  'scapula': ['escápula', 'f'],
  'humerus': ['úmero', 'm'],
  'femur': ['fêmur', 'm'],
  'tibia': ['tíbia', 'f'],
  'fibula': ['fíbula', 'f'],
  'patella': ['patela', 'f'],
  'sacrum': ['sacro', 'm'],
  'coccyx': ['cóccix', 'm'],
  'mandible': ['mandíbula', 'f'],
  'maxilla': ['maxila', 'f'],
  'constrictor': ['constritor', 'm'],
  'flexor': ['flexor', 'm'],
  'extensor': ['extensor', 'm'],
  'abductor': ['abdutor', 'm'],
  'adductor': ['adutor', 'm'],
  'rotator': ['rotador', 'm'],
  'levator': ['levantador', 'm'],
  'depressor': ['depressor', 'm'],
  'dilator': ['dilatador', 'm'],
  'obturator': ['obturador', 'm'],
};

// ─── Adjectives — with masc/fem forms [masc, fem] ───

const ADJECTIVES: Record<string, [string, string]> = {
  'right': ['direito', 'direita'],
  'left': ['esquerdo', 'esquerda'],
  'anterior': ['anterior', 'anterior'],
  'posterior': ['posterior', 'posterior'],
  'superior': ['superior', 'superior'],
  'inferior': ['inferior', 'inferior'],
  'medial': ['medial', 'medial'],
  'lateral': ['lateral', 'lateral'],
  'proximal': ['proximal', 'proximal'],
  'distal': ['distal', 'distal'],
  'superficial': ['superficial', 'superficial'],
  'deep': ['profundo', 'profunda'],
  'internal': ['interno', 'interna'],
  'external': ['externo', 'externa'],
  'dorsal': ['dorsal', 'dorsal'],
  'ventral': ['ventral', 'ventral'],
  'central': ['central', 'central'],
  'upper': ['superior', 'superior'],
  'lower': ['inferior', 'inferior'],
  'ascending': ['ascendente', 'ascendente'],
  'descending': ['descendente', 'descendente'],
  'transverse': ['transverso', 'transversa'],
  'oblique': ['oblíquo', 'oblíqua'],
  'common': ['comum', 'comum'],
  'proper': ['próprio', 'própria'],
  'major': ['maior', 'maior'],
  'minor': ['menor', 'menor'],
  'long': ['longo', 'longa'],
  'short': ['curto', 'curta'],
  'great': ['grande', 'grande'],
  'small': ['pequeno', 'pequena'],
  'middle': ['médio', 'média'],
  'basal': ['basal', 'basal'],
  'apical': ['apical', 'apical'],
  'marginal': ['marginal', 'marginal'],
  'circumflex': ['circunflexo', 'circunflexa'],
  'recurrent': ['recorrente', 'recorrente'],
  'communicating': ['comunicante', 'comunicante'],
  'free': ['livre', 'livre'],
  'cervical': ['cervical', 'cervical'],
  'thoracic': ['torácico', 'torácica'],
  'lumbar': ['lombar', 'lombar'],
  'sacral': ['sacral', 'sacral'],
  'cranial': ['craniano', 'craniana'],
  'spinal': ['espinhal', 'espinhal'],
  'cerebral': ['cerebral', 'cerebral'],
  'cerebellar': ['cerebelar', 'cerebelar'],
  'coronary': ['coronário', 'coronária'],
  'hepatic': ['hepático', 'hepática'],
  'renal': ['renal', 'renal'],
  'pulmonary': ['pulmonar', 'pulmonar'],
  'gastric': ['gástrico', 'gástrica'],
  'biliary': ['biliar', 'biliar'],
  'pancreatic': ['pancreático', 'pancreática'],
  'urinary': ['urinário', 'urinária'],
  'cardiac': ['cardíaco', 'cardíaca'],
  'aortic': ['aórtico', 'aórtica'],
  'carotid': ['carótido', 'carótida'],
  'jugular': ['jugular', 'jugular'],
  'femoral': ['femoral', 'femoral'],
  'tibial': ['tibial', 'tibial'],
  'radial': ['radial', 'radial'],
  'ulnar': ['ulnar', 'ulnar'],
  'brachial': ['braquial', 'braquial'],
  'axillary': ['axilar', 'axilar'],
  'iliac': ['ilíaco', 'ilíaca'],
  'inguinal': ['inguinal', 'inguinal'],
  'popliteal': ['poplíteo', 'poplítea'],
  'subclavian': ['subclávio', 'subclávia'],
  'humeral': ['umeral', 'umeral'],
  'scapular': ['escapular', 'escapular'],
  'deltoid': ['deltoide', 'deltoide'],
  'pectoral': ['peitoral', 'peitoral'],
  'abdominal': ['abdominal', 'abdominal'],
  'epigastric': ['epigástrico', 'epigástrica'],
  'mesenteric': ['mesentérico', 'mesentérica'],
  'colic': ['cólico', 'cólica'],
  'pharyngeal': ['faríngeo', 'faríngea'],
  'laryngeal': ['laríngeo', 'laríngea'],
  'bronchial': ['brônquico', 'brônquica'],
  'bronchopulmonary': ['broncopulmonar', 'broncopulmonar'],
  'nasal': ['nasal', 'nasal'],
  'orbital': ['orbital', 'orbital'],
  'optic': ['óptico', 'óptica'],
  'ocular': ['ocular', 'ocular'],
  'temporal': ['temporal', 'temporal'],
  'frontal': ['frontal', 'frontal'],
  'parietal': ['parietal', 'parietal'],
  'occipital': ['occipital', 'occipital'],
  'lacrimal': ['lacrimal', 'lacrimal'],
  'ciliary': ['ciliar', 'ciliar'],
  'choroidal': ['coroidal', 'coroidal'],
  'synovial': ['sinovial', 'sinovial'],
  'costal': ['costal', 'costal'],
  'intercostal': ['intercostal', 'intercostal'],
  'pelvic': ['pélvico', 'pélvica'],
  'venous': ['venoso', 'venosa'],
  'arterial': ['arterial', 'arterial'],
  'lymphatic': ['linfático', 'linfática'],
  'nervous': ['nervoso', 'nervosa'],
  'muscular': ['muscular', 'muscular'],
  'skeletal': ['esquelético', 'esquelética'],
  'anatomical': ['anatômico', 'anatômica'],
  'segmental': ['segmentar', 'segmentar'],
  'subsegmental': ['subsegmentar', 'subsegmentar'],
  'lobar': ['lobar', 'lobar'],
  'lobular': ['lobular', 'lobular'],
  'lingular': ['lingular', 'lingular'],
  'collateral': ['colateral', 'colateral'],
  'intervertebral': ['intervertebral', 'intervertebral'],
  'interventricular': ['interventricular', 'interventricular'],
  'atrioventricular': ['atrioventricular', 'atrioventricular'],
  'interosseous': ['interósseo', 'interóssea'],
  'metacarpal': ['metacarpal', 'metacarpal'],
  'metatarsal': ['metatarsal', 'metatarsal'],
  'tarsal': ['tarsal', 'tarsal'],
  'carpal': ['carpal', 'carpal'],
  'palmar': ['palmar', 'palmar'],
  'plantar': ['plantar', 'plantar'],
  'digital': ['digital', 'digital'],
  'papillary': ['papilar', 'papilar'],
  'genicular': ['genicular', 'genicular'],
  'portal': ['portal', 'portal'],
  'callosomarginal': ['calosomarginal', 'calosomarginal'],
  'secondary': ['secundário', 'secundária'],
  'molar': ['molar', 'molar'],
  'premolar': ['pré-molar', 'pré-molar'],
  'incisor': ['incisivo', 'incisiva'],
  'canine': ['canino', 'canina'],
  'cuneiform': ['cuneiforme', 'cuneiforme'],
  'systemic': ['sistêmico', 'sistêmica'],
  'vascular': ['vascular', 'vascular'],
  'variant': ['variante', 'variante'],
  'septal': ['septal', 'septal'],
  'diagonal': ['diagonal', 'diagonal'],
  'ventricular': ['ventricular', 'ventricular'],
  'investing': ['investidura', 'investidura'],
  'caudate': ['caudado', 'caudada'],
  'pontine': ['pontino', 'pontina'],
  'cecal': ['cecal', 'cecal'],
  'costocervical': ['costocervical', 'costocervical'],
  'subcostal': ['subcostal', 'subcostal'],
  'precentral': ['pré-central', 'pré-central'],
  'postcentral': ['pós-central', 'pós-central'],
  'frontobasal': ['frontobasal', 'frontobasal'],
  'thoraco-acromial': ['toracoacromial', 'toracoacromial'],
  'duodenal': ['duodenal', 'duodenal'],
  'jejunal': ['jejunal', 'jejunal'],
  'ileal': ['ileal', 'ileal'],
  'rectal': ['retal', 'retal'],
  'sigmoid': ['sigmoide', 'sigmoide'],
  'splenic': ['esplênico', 'esplênica'],
  'ovarian': ['ovariano', 'ovariana'],
  'testicular': ['testicular', 'testicular'],
  'vesical': ['vesical', 'vesical'],
  'uterine': ['uterino', 'uterina'],
  'vaginal': ['vaginal', 'vaginal'],
  'perineal': ['perineal', 'perineal'],
  'gluteal': ['glúteo', 'glútea'],
  'suprascapular': ['supraescapular', 'supraescapular'],
  'infraorbital': ['infraorbital', 'infraorbital'],
  'supraorbital': ['supraorbital', 'supraorbital'],
  'submental': ['submental', 'submental'],
  'sublingual': ['sublingual', 'sublingual'],
  'submandibular': ['submandibular', 'submandibular'],
  'supraclavicular': ['supraclavicular', 'supraclavicular'],
  'infraclavicular': ['infraclavicular', 'infraclavicular'],
  'subscapular': ['subescapular', 'subescapular'],
  'suprarenal': ['suprarrenal', 'suprarrenal'],
  'infrarenal': ['infrarrenal', 'infrarrenal'],
  'retroperitoneal': ['retroperitoneal', 'retroperitoneal'],
  'intraperitoneal': ['intraperitoneal', 'intraperitoneal'],
  'intrapulmonary': ['intrapulmonar', 'intrapulmonar'],
  'extrapulmonary': ['extrapulmonar', 'extrapulmonar'],
  'intracranial': ['intracraniano', 'intracraniana'],
  'extracranial': ['extracraniano', 'extracraniana'],
  'paravertebral': ['paravertebral', 'paravertebral'],
  'postvertebral': ['pós-vertebral', 'pós-vertebral'],
  'prevertebral': ['pré-vertebral', 'pré-vertebral'],
  'vertebral': ['vertebral', 'vertebral'],
  'intrinsic': ['intrínseco', 'intrínseca'],
  'extrinsic': ['extrínseco', 'extrínseca'],
  'horizontal': ['horizontal', 'horizontal'],
  'vertical': ['vertical', 'vertical'],
  'little': ['mínimo', 'mínima'],
  'index': ['indicador', 'indicadora'],
};

// Ordinals
const ORDINALS: Record<string, string> = {
  'first': 'primeiro',
  'second': 'segundo',
  'third': 'terceiro',
  'fourth': 'quarto',
  'fifth': 'quinto',
  'sixth': 'sexto',
  'seventh': 'sétimo',
  'eighth': 'oitavo',
  'ninth': 'nono',
  'tenth': 'décimo',
  'eleventh': 'décimo primeiro',
  'twelfth': 'décimo segundo',
};

// Action words (flexor, extensor etc) — treated as nouns (masculine)
const ACTION_NOUNS: Record<string, string> = {
  'flexor': 'flexor',
  'extensor': 'extensor',
  'abductor': 'abdutor',
  'adductor': 'adutor',
  'rotator': 'rotador',
  'levator': 'levantador',
  'depressor': 'depressor',
  'constrictor': 'constritor',
  'dilator': 'dilatador',
  'obturator': 'obturador',
};

// Latin terms kept as-is or lightly adapted
const LATIN_TERMS: Record<string, string> = {
  'longus': 'longo',
  'brevis': 'curto',
  'magnus': 'magno',
  'minimus': 'mínimo',
  'maximus': 'máximo',
  'medius': 'médio',
  'rectus': 'reto',
  'teres': 'redondo',
  'capitis': 'da cabeça',
  'cervicis': 'do pescoço',
  'thoracis': 'do tórax',
  'femoris': 'do fêmur',
  'brachii': 'do braço',
  'carpi': 'do carpo',
  'pollicis': 'do polegar',
  'hallucis': 'do hálux',
  'digiti': 'do dedo',
  'digitorum': 'dos dedos',
  'minimi': 'mínimo',
  'indicis': 'do indicador',
  'radialis': 'radial',
  'ulnaris': 'ulnar',
};

// Words to skip / translate to nothing
const SKIP_WORDS = new Set(['the', 'a', 'an']);

// Prepositions
const PREPOSITIONS: Record<string, string> = {
  'of': 'de',
  'and': 'e',
  'or': 'ou',
  'with': 'com',
  'in': 'em',
  'on': 'em',
  'for': 'para',
  'to': 'para',
  'from': 'de',
  'by': 'por',
  'at': 'em',
};

function translateWord(w: string): string {
  const lower = w.toLowerCase();
  if (SKIP_WORDS.has(lower)) return '';
  if (PREPOSITIONS[lower]) return PREPOSITIONS[lower];
  if (ORDINALS[lower]) return ORDINALS[lower];
  if (LATIN_TERMS[lower]) return LATIN_TERMS[lower];
  if (ACTION_NOUNS[lower]) return ACTION_NOUNS[lower];

  const noun = NOUNS[lower];
  if (noun) return noun[0];

  const adj = ADJECTIVES[lower];
  if (adj) return adj[0]; // default to masculine, gender adjusted later

  return w;
}

function findHeadNoun(words: string[]): [string, Gender] | null {
  for (let i = words.length - 1; i >= 0; i--) {
    const n = NOUNS[words[i].toLowerCase()];
    if (n) return n;
  }
  return null;
}

function genderAdjective(word: string, gender: Gender): string {
  const lower = word.toLowerCase();
  const adj = ADJECTIVES[lower];
  if (adj) return gender === 'f' ? adj[1] : adj[0];
  return translateWord(word);
}

function translatePhrase(phrase: string): string {
  const words = phrase.trim().split(/\s+/);
  if (words.length === 0) return phrase;

  const headNoun = findHeadNoun(words);
  const gender: Gender = headNoun ? headNoun[1] : 'm';

  const translated = words.map(w => {
    const lower = w.toLowerCase();
    if (SKIP_WORDS.has(lower)) return '';
    if (ORDINALS[lower]) return ORDINALS[lower];
    if (LATIN_TERMS[lower]) return LATIN_TERMS[lower];
    if (ACTION_NOUNS[lower]) return ACTION_NOUNS[lower];
    const noun = NOUNS[lower];
    if (noun) return noun[0];
    return genderAdjective(w, gender);
  }).filter(Boolean);

  if (translated.length <= 1) return translated[0] || phrase;

  // Reorder: find the noun position, move adjectives after it
  // In English anatomy: [adj...] [noun] → Portuguese: [noun] [adj...]
  const nounIdx = (() => {
    for (let i = translated.length - 1; i >= 0; i--) {
      const orig = words[i]?.toLowerCase();
      if (orig && NOUNS[orig]) return i;
    }
    return -1;
  })();

  if (nounIdx >= 0 && nounIdx < translated.length) {
    const noun = translated[nounIdx];
    const before = translated.slice(0, nounIdx);
    const after = translated.slice(nounIdx + 1);
    const allAdjs = [...before, ...after];

    // Move side adjectives (direito/esquerdo) to the end
    const SIDE_WORDS = new Set(['direito', 'direita', 'esquerdo', 'esquerda']);
    const sideAdjs = allAdjs.filter(a => SIDE_WORDS.has(a.toLowerCase()));
    const otherAdjs = allAdjs.filter(a => !SIDE_WORDS.has(a.toLowerCase()));

    return [noun, ...otherAdjs, ...sideAdjs].join(' ');
  }

  return translated.join(' ');
}

function detectGender(translated: string): Gender | null {
  const words = translated.split(/\s+/);
  for (const w of words) {
    for (const [, [pt, g]] of Object.entries(NOUNS)) {
      if (pt.toLowerCase() === w.toLowerCase()) return g;
    }
  }
  return null;
}

function contractPreposition(translated: string): string {
  const gender = detectGender(translated);
  if (gender === 'f') return `da ${translated}`;
  if (gender === 'm') return `do ${translated}`;
  return `de ${translated}`;
}

function translateSegment(en: string): string {
  const key = en.toLowerCase().trim();
  if (OVERRIDES[key]) return OVERRIDES[key];
  return translatePhrase(en);
}

function lowercaseFirst(s: string): string {
  return s[0].toLowerCase() + s.slice(1);
}

function capitalize(s: string): string {
  return s[0].toUpperCase() + s.slice(1);
}

export function translateName(en: string): string {
  const key = en.toLowerCase().trim();
  if (OVERRIDES[key]) return OVERRIDES[key];

  // Split by " of " into segments: "branch of right coronary artery" → ["branch", "right coronary artery"]
  const segments = en.split(/\s+of\s+/i);

  if (segments.length === 1) {
    return capitalize(translatePhrase(en));
  }

  // Try progressively larger tail segments as overrides
  for (let i = 1; i < segments.length; i++) {
    const tail = segments.slice(i).join(' of ');
    const tailKey = tail.toLowerCase().trim();
    if (OVERRIDES[tailKey]) {
      const headEn = segments.slice(0, i).join(' of ');
      const head = translateSegment(headEn);
      return capitalize(`${head} ${contractPreposition(lowercaseFirst(OVERRIDES[tailKey]))}`);
    }
  }

  // Translate each segment individually, then join with "de/da/do"
  const translatedSegments = segments.map(s => translateSegment(s));

  let result = translatedSegments[0];
  for (let i = 1; i < translatedSegments.length; i++) {
    result += ' ' + contractPreposition(lowercaseFirst(translatedSegments[i]));
  }

  return capitalize(result);
}

export function translateAtlas(atlas: Atlas): Atlas {
  for (const part of atlas.parts) {
    part.name = translateName(part.name);
  }
  for (const concept of atlas.concepts) {
    concept.name = translateName(concept.name);
  }
  return atlas;
}
